// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2i_eGBFivxzKxE9q5xOMkp1I8Pku2mSM',
    appId: '1:283790914572:web:67a356131cfbf015552a29',
    messagingSenderId: '283790914572',
    projectId: 'shop-8ab41',
    authDomain: 'shop-8ab41.firebaseapp.com',
    storageBucket: 'shop-8ab41.appspot.com',
    measurementId: 'G-1L7DHZ7JSF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmkVsw0IfUZBoc2FLF4C1HsNAEhBrDN-k',
    appId: '1:283790914572:android:907dc3e95b95edab552a29',
    messagingSenderId: '283790914572',
    projectId: 'shop-8ab41',
    storageBucket: 'shop-8ab41.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDE9hY9LBHRcFs5FbvZ5rg5OhlgTXKriMs',
    appId: '1:283790914572:ios:1da8709cee6d16e7552a29',
    messagingSenderId: '283790914572',
    projectId: 'shop-8ab41',
    storageBucket: 'shop-8ab41.appspot.com',
    iosBundleId: 'com.example.service',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDE9hY9LBHRcFs5FbvZ5rg5OhlgTXKriMs',
    appId: '1:283790914572:ios:af0da0dca51e42d7552a29',
    messagingSenderId: '283790914572',
    projectId: 'shop-8ab41',
    storageBucket: 'shop-8ab41.appspot.com',
    iosBundleId: 'com.example.service.RunnerTests',
  );
}
